# Copyright (C) 2020 
# Authors: Ricardo Arguello, Misael Fern\u00e1ndez
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.*
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#5 seconds
time_out = 10000
cfg = https://mirror.cedia.org.ec/firmaec/cfg.zip
#cfg = https://www.firmadigital.gob.ec/firmaec/cfg.zip
font.courier=fonts/courier.ttf
font.courier_bold=fonts/courier-bold.ttf
font.helvetica=fonts/inter.ttf

#version_url = http://testapi.firmadigital.gob.ec:8080/api/version
#fecha_hora_url = http://testapi.firmadigital.gob.ec:8080/api/fecha-hora
#certificado_revocado_url = http://testapi.firmadigital.gob.ec:8080/api/certificado/fechaRevocado
#version_url = https://impapi.firmadigital.gob.ec/api/version
#fecha_hora_url = https://impapi.firmadigital.gob.ec/api/fecha-hora
#certificado_revocado_url = https://impapi.firmadigital.gob.ec/api/certificado/fechaRevocado
version_url = https://api.firmadigital.gob.ec/api/version
fecha_hora_url = https://api.firmadigital.gob.ec/api/fecha-hora
certificado_revocado_url = https://api.firmadigital.gob.ec/api/certificado/fechaRevocado

version=4.2.0
fecha=2026-01-31